### ISSUE TITLE
IMA@18

### ISSUE THREAD

**Issue by jsimck** [seznam/ima#208]
This issue tracks progress towards IMA@18 release.

### Missing features
- [x] Add options to disable build of `legacy` version from `ima.config.js`
- [x] Migrate to new version of message format #206 

### Known issues
- [x] ~~Currently dynamic imports don't work on server-side.~~ (works)
- [x] When error-overlay displays compile error and the browser window is refreshed, there's blank page, instead of SSR rendered error overlay for compile error, as it's done with the runtime SSR error overlay (not sure if this can be done easily). (Fixed in #210)
- [x] README and documentation missing for new packages (`@ima/cli`, `@ima/dev-utils`, `@ima/error-overlay`, `@ima/hmr-client`).
- [x] `extractSourceMappingUrl` in `@ima/dev-utils` can probably be simplified. https://github.com/seznam/ima/pull/218 (works as intented, replaces `source-map` with `source-map-js` pkg
- [x] **node 18** support (drop node-fetch dependency in favor of native implementation of fetch in node 18). (Fixed in #210)
- [x] Kill already running applications on the same port when running `npm run dev` (e.g. already running app on 3001 is closed before starting new one, so `npm run dev` never fails in these situations). https://github.com/seznam/ima/pull/213
- [x] **Drop node-fetch**, use native fetch from node 18 by default. https://github.com/seznam/ima/pull/212

### Potential improvements (don't need to be ready for IMA@18 release)
- [x] Refactor `@ima/helpers` to esm. https://github.com/seznam/ima/pull/214
- [ ] #261
- [ ] Define `exports` fields in package.json on `@ima/dev-utils` to have nicer imports along with Typescript 4.7 update (when released)
- [x] ~~Auto generate $Runner assets ($Source) at build-time (GenerateRunnerPlugin extension)~~
  * ~~Content hashes can be used in this case for cache busing, instead of the `?v=[version]` param (this results in faster load times in dev)~~
  * ~~We would no longer need to define $Source asset paths in `environment.js`, however we still need to have an option to define custom attributes or conditional renders for each asset.~~
- [x] ~~Try to get `webpack-dev-middleware` to work with in-memory assets only. Currently every HMR update is written~~ ~~and served from disk. `webpack-dev-middleware` has an option to serve these updates directly from memory using `memfs`. (may have something to do with https://github.com/webpack/webpack/issues/15206)~~

#### core
- [ ] globals from setupFile are not visible to TS compiler (using, extend), some tests are commented out
- [x] RouteOptions type is defined in core but is using ComponentType from react - core should not have react dependency

#### react-page-renderer
- [ ] some tests with jest fake timers do not work (timeout) and are commented out
- [x] jest.config.js needs polishing (copy config from core)
- [x] types from core has to be removed in favor of new defition files from core (after core is in TS)
- [x] ClientPageRenderer and LegacyClientPageRenderer has to be removed from index.ts and compiled separately

This issue will be updated as new fixes/features are merged to next or new issues are discovered.

**Comment by jsimck** [comment]
Most issues have been resolved, others are outdated.
