### ISSUE TITLE
TypeScript - Types tracking issue

### ISSUE THREAD

**Issue by jsimck** [seznam/ima#478]
This issue represents TODO list which will be updated periodically, with tasks that should be fixed in order to improve ima TS typing

- [ ] Improve object container typing
- [ ] Fix Controller and extension types across the board (sometimes the types expect instance but are typed with constructor and the other way around)
- [x] Add State generic definition to Page controller (similar to how react class components are done)
- [x] Add Generics to page state manager
